# Generated by Django 3.0.3 on 2020-02-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=70, unique=True, verbose_name='Наименование курса')),
                ('course_slug', models.SlugField(max_length=200, unique=True, verbose_name='Слег')),
                ('is_course_active', models.BooleanField(default=False, verbose_name='Курс доступен')),
                ('course_short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('course_overview', models.TextField(verbose_name='Описание')),
                ('course_duration', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('course_price', models.IntegerField(verbose_name='Цена')),
                ('course_creation_date', models.DateField(auto_now_add=True)),
                ('course_version', models.IntegerField(verbose_name='Версия курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['course_title'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=70, unique=True, verbose_name='Название категории')),
                ('category_slug', models.SlugField(max_length=200, unique=True, verbose_name='Слег')),
                ('is_category_active', models.BooleanField(default=False, verbose_name='Активная категория')),
            ],
            options={
                'verbose_name': 'Категори',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_title'],
            },
        ),
        migrations.CreateModel(
            name='CourseFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_start_date', models.DateField(verbose_name='Дата начала')),
                ('course_code', models.CharField(max_length=50, unique=True, verbose_name='Код потока')),
                ('is_course_over', models.BooleanField(default=False, verbose_name='Поток завершен')),
            ],
            options={
                'verbose_name': 'Поток (набор) курса',
                'verbose_name_plural': 'Потоки курсов',
                'ordering': ['course_start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseFlowTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateTimeField(verbose_name='Дата занятия')),
            ],
            options={
                'verbose_name': 'Расписание занятий',
                'verbose_name_plural': 'Расписание занятий',
            },
        ),
        migrations.CreateModel(
            name='CourseStudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100, verbose_name='Тема занятия')),
                ('lesson_number', models.IntegerField(verbose_name='Порядковый Номер занятия в курсе')),
                ('lesson_description', models.TextField(verbose_name='Описание занятия')),
                ('is_lesson_active', models.BooleanField(default=False, verbose_name='Доступность')),
                ('lesson_version', models.IntegerField(default=1, verbose_name='Версия урока')),
            ],
            options={
                'verbose_name': 'Учебный план курса',
                'verbose_name_plural': 'Учебные планы курсов',
                'ordering': ['lesson_title'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_title', models.CharField(max_length=200, verbose_name='Название')),
                ('homework_number', models.IntegerField(default=1, verbose_name='Порядковый номер в курсе')),
                ('homework_description', models.TextField(verbose_name='Описание')),
                ('due_date', models.DateField(verbose_name='Срок сдачи')),
                ('is_homework_active', models.BooleanField(default=False, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='StudentsAcademicPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_completion', models.DateField(blank=True, null=True, verbose_name='Факт дата сдачи')),
                ('homework_status', models.CharField(choices=[('NOT_DONE', 'not done'), ('ON_REVIEW', 'on review'), ('SEND_TO_REWORK', 'send to rework'), ('COMPLETE', 'complete')], default='NOT_DONE', max_length=20, verbose_name='Статус работы')),
                ('teacher_comments', models.TextField(blank=True, verbose_name='Комментарии преподавателя')),
            ],
            options={
                'verbose_name': 'Успеваемость студентов',
                'verbose_name_plural': 'Успеваемость студентов',
            },
        ),
        migrations.CreateModel(
            name='StudentsInCourseFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_learning_date', models.DateField(verbose_name='Дата начала обучения')),
                ('is_student_active', models.BooleanField(default=True, verbose_name='Учится\\отчислен')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseFlows', verbose_name='Поток курса')),
            ],
            options={
                'verbose_name': 'Студенты в потоке',
                'verbose_name_plural': 'Студенты в потоке',
            },
        ),
    ]
