# Generated by Django 3.0.3 on 2020-02-10 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsincourseflow',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='studentsacademicperformance',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseFlows', verbose_name='Поток курса'),
        ),
        migrations.AddField(
            model_name='studentsacademicperformance',
            name='homework_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Homework', verbose_name='Дом задание'),
        ),
        migrations.AddField(
            model_name='studentsacademicperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.StudentsInCourseFlow', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='homework',
            name='course_flow_attached',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseFlows', verbose_name='Поток курса'),
        ),
        migrations.AddField(
            model_name='coursestudyplan',
            name='course_attached',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courseflowtimetable',
            name='course_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseFlows', verbose_name='Поток курса'),
        ),
        migrations.AddField(
            model_name='courseflowtimetable',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseStudyPlan', verbose_name='Номер занятия'),
        ),
        migrations.AddField(
            model_name='courseflowtimetable',
            name='lesson_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='courseflows',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courseflows',
            name='course_curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseCategories', verbose_name='Категория'),
        ),
    ]
