# Generated by Django 3.0.3 on 2020-02-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200210_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Изображение'),
        ),
    ]
